version: 2
jobs:
  build:
    docker:
      - image: cibuilds/github:0.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Git
          command: git diff HEAD^1
