version: 2
jobs:
  update_image:
    docker:
      - image: circleci/python:3.7.2
    working_directory: /home/circleci/src
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          command: |
            git clone git@github.com:atanner27/test-git-merge.git
      - run:
          name: Detect Base Image Changes 
          command: |
            docker pull gcr.io/google-appengine/python:latest
            NEW_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' gcr.io/google-appengine/python:latest)
            echo $NEW_SHA
            OLD_SHA=$(cat ./Dockerfile | grep "FROM" | awk '{print $2}')
            echo $OLD_SHA
            if [ "$OLD_SHA" != "$NEW_SHA" ]; then
                sed -i 's/$OLD_SHA/NEW_SHA/g' ./Dockerfile
                git add ./Dockerfile
                git commit -m "Modified Base Image to $OLD_SHA"
            fi

workflows:
  version: 2
  build:
    jobs:
      - update_image:
          filters:
            tags:
              only: master

  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - update_image
 
